### ISSUE TITLE
Bug queuing 'hydrore whitefists'

### ISSUE THREAD

**Issue by stevethewright** [Ethang70/Dice-Bot#55]
Check logs

**Comment by Ethang70** [comment]
Bot used to let user know when song can't be found. But the way its handled is broken now :)

**Comment by Ethang70** [comment]
While the function of the bot was unaffected when this error occurs the bot now properly notifies the user when it can't find their track. 


Also other bugs with the player were found in which users not connected to the voice chat could queue songs. Also those users were not notified when interacting that they are not in the correct channel, etc. These have been fixed.
